apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite318b
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-rocm-runtime
      storageUri: oci://quay.io/spolti/granite-3.1-8b:instruct
      args:
        - --max-model-len=20000
        - '--dtype=bfloat16'
        - '--model=/mnt/models'
        - '--tensor-parallel-size=1'
        - '--uvicorn-log-level=debug'
        - '--served-model-name=granite318b'
      resources:
        limits:
          amd.com/gpu: 1
        requests:
          amd.com/gpu: 1