apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
spec:
  endpoints:
    - bearerTokenSecret:
        key: ''
      interval: 30s
      port: http-monitoring
  namespaceSelector: {}
  selector:
    matchLabels:
      istio: pilot
  targetLabels:
    - app
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
spec:
  namespaceSelector: {}
  selector:
    matchExpressions:
      - key: istio-prometheus-ignore
        operator: DoesNotExist
  podMetricsEndpoints:
    - bearerTokenSecret:
        key: ''
      interval: 30s
      path: /stats/prometheus
