# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: perses-sa
  namespace: monitoring
---
# service account token secret
apiVersion: v1
kind: Secret
metadata:
  name: perses-sa-token
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: perses-sa
type: kubernetes.io/service-account-token
---
# cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: perses-sa-cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: perses-sa
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
---