# grafana
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: openshift-user-workload-monitoring
  labels:
    dashboards: "grafana"
    folders: "grafana"
spec:
  config:
    auth:
      disable_login_form: "false"
      disable_signout_menu: "true"
    auth.anonymous:
      enabled: "false"
    security:
      admin_user: "admin"
      admin_password: "admin"
    log:
      level: warn
      mode: console