apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-dynamic-pvc
spec:
  accessModes:
    - ReadWriteMany
  #storageClassName: standard  # keep commented to use your cluster's default storage class
  resources:
    requests:
      storage: 1Gi