# apiVersion: serving.kserve.io/v1beta1
# kind: InferenceService
# metadata:
#   name: sklearn-example
# spec:
#   predictor:
#     model:
#       runtime: mlserver-1.x
#       protocolVersion: grpc-v2
#       modelFormat:
#         name: sklearn
#       storage:
#         key: localMinIO
#         path: sklearn/mnist-svm.joblib
#         parameters:
#           bucket: modelmesh-example-models
#---
# apiVersion: serving.kserve.io/v1beta1
# kind: InferenceService
# metadata:
#   name: example-onnx-mnist
# spec:
#   predictor:
#     model:
#       modelFormat:
#         name: onnx
#       runtime: ovms-1.x
#       storage:
#         key: localMinIO
#         path: onnx/mnist.onnx
---
# apiVersion: "serving.kserve.io/v1beta1"
# kind: "InferenceService"
# metadata:
#   name: "sklearn-iris"
# spec:
#   predictor:
#     model:
#       runtime: mlserver-1.x
#       protocolVersion: v2
#       modelFormat:
#         name: sklearn
#       storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris-instance-2"
  annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
spec:
  predictor:
    model:
      runtime: kserve-mlserver
      # protocolVersion: v2
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
      env:
        - name: MODEL_NAME
          value: "sklearn-iris"
        - name: MODEL_URI
          value: "gs://kfserving-examples/models/sklearn/1.0/model"
        - name: MODEL_VERSION
          value: "1.0"
        - name: MODEL_CLASS
          value: "sklearn"
        - name: MODEL_HANDLER
          value: "predict"
        - name: MODEL_TYPE  
          value: "sklearn"
        - name: MODEL_RUNTIME
          value: "mlserver-1.x"