apiVersion: v1
kind: Secret
metadata:
  name: storage-config
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "AKIAIOSFODNN7EXAMPLE",
      "secret_access_key": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
      "endpoint_url": "http://minio.kserve-test:9000",
      "default_bucket": "modelmesh-example-models",
      "region": "us-south"
    }

# ---
# or
#  oc apply -n fspolti -f - <<YAML
# apiVersion: v1
# kind: Secret
# metadata:
#   name: storage-config
# stringData: 
#   aws-connection-minio: |
#     {
#       "type": "s3",
#       "access_key_id": "admin",
#       "secret_access_key": "password",
#       "endpoint_url": "MINIO_S3_SVC_URL",
#       "region": "us-east-2"
#        "default_bucket": "modelmesh-example-models",
#     }
# YAML

# ---
#or
# apiVersion: v1
# kind: Secret
# metadata:
#   annotations:
#     serving.kserve.io/s3-endpoint: minio.fspolti.svc:9000 # replace with your s3 endpoint e.g minio-service.kubeflow:9000
#     serving.kserve.io/s3-usehttps: "0" # by default 1, if testing with minio you can set to 0
#     serving.kserve.io/s3-region: "us-east-2"
#     serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
#   name: storage-config
# stringData:
#   "AWS_ACCESS_KEY_ID": "admin"
#   "AWS_SECRET_ACCESS_KEY": "password"