apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: mlserver-runtime
  annotations:
    serving.kserve.io/server-type: mlserver
spec:
  annotations:
    prometheus.kserve.io/port: '8082'
    prometheus.kserve.io/path: /metrics
  containers:
    - name: kserve-container
      image: quay.io/opendatahub/mlserver:odh-v3.4 
      env:
        - name: MLSERVER_MODEL_NAME
          value: sentiment-analysis
        - name: MLSERVER_MODEL_IMPLEMENTATION
          value: mlserver_onnx.OnnxModel
        - name: MLSERVER_MODEL_URI
          value: /mnt/models
        - name: MLSERVER_HTTP_PORT
          value: '8080'
        - name: MLSERVER_MODELS_DIR
          value: /mnt/models
      startupProbe:
        initialDelaySeconds: 1
        periodSeconds: 1
        failureThreshold: 1
        exec:
          command:
            - /bin/sh
            - -c
            - |
              [ -n "$(ls -A /mnt/models 2>/dev/null)" ]
      readinessProbe:
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
        timeoutSeconds: 5
        httpGet:
          path: /v2/models/sentiment-analysis/ready
          port: 8080
      livenessProbe:
        initialDelaySeconds: 20
        periodSeconds: 10
        failureThreshold: 6
        timeoutSeconds: 5
        httpGet:
          path: /v2/models/sentiment-analysis/ready
          port: 8080
      ports:
        - containerPort: 8080
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsNonRoot: true
  protocolVersions:
    - v2
  multiModel: false
  supportedModelFormats:
    - name: onnx
      version: '1'
    - name: sklearn
      version: '0'
    - name: sklearn
      version: '1'
    - name: xgboost
      version: '1'
    - name: xgboost
      version: '2'
    - name: lightgbm
      version: '3'
    - name: lightgbm
      version: '4'
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sentiment-analysis
  annotations:
    serving.kserve.io/deploymentMode: "Standard"
    security.opendatahub.io/enable-auth: "true"
  labels:
    networking.kserve.io/visibility: exposed 
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      runtime: mlserver-runtime
      storageUri: "hf://optimum/distilbert-base-uncased-finetuned-sst-2-english"
  transformer:
    containers:
    - name: kserve-container
      image: quay.io/spolti/kserve-sentiment-custom-transformer@sha256:cd8c290d0860e0b67dbd4138bc985e5f895da2c8e4eac3644fdb4a16520a8495
      args:
      - --model-name=sentiment-analysis
      - --tokenizer_name=optimum/distilbert-base-uncased-finetuned-sst-2-english
      - --sentiment_labels=negative,positive
      - --max_length=128
      - --input_names=input_ids,attention_mask
      - --output_name=predict
      - --include_star_rating