apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite318b
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      storageUri: quay.io/spolti/granite-3.1-8b:instruct
      args:
        - --dtype=half
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1