# Gateway infrastructure parameters. Apply in openshift-ingress.
# serving-cert-secret-name must match the Gateway TLS secret.
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${GATEWAY_OPTIONS_CONFIGMAP}
  namespace: ${GATEWAY_NAMESPACE}
data:
  service: |
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: "${CERT_NAME}"
    # remove this for ROSA clusters    
    spec:
      type: ClusterIP
